//
//  SESSION_AUTHENTICATION_UNSUPPORTED_AUTHENTICATION_METHOD.swift
//  up-english
//
//  Created by James Tsai on 6/23/22.
//

import Foundation

class SESSION_AUTHENTICATION_UNSUPPORTED_AUTHENTICATION_METHOD: SESSION_AUTHENTICATION_ERROR {
    
}
